/**
 *  CONFIG FILE TO CHANGE FOR USER BEFORE COMPILATION
 *
 */


// DEFINE YOUR CUBE SIZE (N IN NxNxN)
#ifndef CUBE_SIZE

#define CUBE_SIZE 10

#endif


// COMMENT THE LINE BELOW IF YOU WANT TO BE ABLE TO PRINT CUBES
// #define NO_CUBE_PRINT

// COMMENT THE LINE BELOW IF YOU WANT TO SEE SOME OF THE LOGS
#define NO_LOG
